<?php include('includes/authenticate.php'); ?>
<?php
	/*$getmaxreg = mysqli_query($dbconnect,"SELECT Max(reg_no) as OPNO FROM tbl_registry");
	$asreg = mysqli_fetch_array($getmaxreg);
	$opnos = $asreg['OPNO'];
	$opno = $opnos+1;
	$opNumber = str_pad($opno,4,"0",STR_PAD_LEFT);
	$result = mysqli_query($dbconnect,"SELECT * FROM tbl_drug_categories");
	$result1 = mysqli_query($dbconnect,"SELECT * FROM tbl_paymentschemes"); */
	?>
<!DOCTYPE html>
<html>

<head>

    <?php include('includes/meta.php');?>
	
    <title>Patient Registry <?php echo "$smart_name"; ?></title>
	
	<meta name="description" content=""/>
	<meta name="keywords" content=""/>
	
	<?php
	$getmaxreg = mysqli_query($dbconnect,"SELECT Max(reg_no) as OPNO FROM tbl_registry");
	$asreg = mysqli_fetch_array($getmaxreg);
	$opnos = $asreg['OPNO'];
	$opno = $opnos+1;
	$opNumber = str_pad($opno,4,"0",STR_PAD_LEFT);
	$result = mysqli_query($dbconnect,"SELECT * FROM tbl_paymentschemes");
	$result1 = mysqli_query($dbconnect,"SELECT * FROM tbl_paymentschemes");
	?>

</head>

<body>
    <div id="wrapper">
    <!-- Navigation -->
	<?php include('includes/sidebar.php');?>
    <!-- Navigation -->

        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
			<?php include('includes/top-nav.php'); ?>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-7">
                    <h2>The Registry</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="registry.php">Registry</a>
                        </li>                        
                        <li class="active">
                            <strong>Add Registry</strong>
                        </li>
                    </ol>
                </div>
					<div class="col-lg-5">
						<p class="pull-right">
						</br>
							<span><a href="registry.php"><button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;<span class="bold"> Back to Patients</span></button></a></span>
						</p>
					</div>
            </div>
			<div class="wrapper wrapper-content">
                <div class="row">					
					<div class="row">	
						<div class="col-lg-7">
						</div>
										
					</div>				
					<div class="col-lg-12">					
                    <div class="ibox float-e-margins">
                        <div class="ibox-content">
						    <div class="modal-body">
											<div class="row">
											<span></span>
												<form role="form" method="post">
												<div class="col-sm-12">													
												<?php
													if(isset($_POST['newpatient1'])){
													echo "jhssssssssssssssssssssssssssssssssssssss";
													}
												?>
												</div>
												
													<div class="col-sm-6">
														<div class="form-group">
															<label>Outpatient Number</label>
															<input type="text" name="OPNO" value="<?php echo "CHMC-OP-$opNumber-23"; ?>" placeholder="to beautogenerated" readonly class="form-control">
														</div>
														<div class="form-group">
															<label>First Name</label>
															<input type="text" name="firstname" required placeholder="First Name" class="form-control">
															
														</div>
														<div class="form-group">
															<label>Last Name</label>
															<input type="text" name="lastname" required placeholder="Last Names" class="form-control">
														</div>
														<div class="form-group">
															<label>Gender</label>
															<select name="gender" class="form-control">
																<option value="">Choose Gender</option>
																<option value="MALE">MALE</option>
																<option value="FEMALE">FEMALE</option>
															</select>
														</div>
														<div class="form-group">
															<label>ADULT/CHILD</label>
															<select name="ageCategory" id="ageCategory" class="form-control">
																<option value="">Choose age Category</option>
																<option value="ADULT">ADULT</option>
																<option value="CHILD">CHILD</option>
																<option value="CHILD">SPECIAL NEED</option>
															</select>
														</div>
														<div class="form-group">
															<label>Date of Birth</label>
															<input type="date" id="dateOfBirth"  name="dob" placeholder="Date of Birth" class="form-control datepicker">
														</div>
														<div class="form-group">
															<label>Age</label>
															<input type="text" id="age" name="agee" placeholder="to be autogenerated" readonly class="form-control">
														</div>

														<script>
															const dateOfBirthInput = document.getElementById("dateOfBirth");
															const ageInput = document.getElementById("age");
															dateOfBirthInput.addEventListener("change", function() {
																const dateOfBirth = new Date(dateOfBirthInput.value);
																const age = calculateAge(dateOfBirth);
																ageInput.value = age;
															});
															function calculateAge(dateOfBirth) {
																const now = new Date();
																const diffInMs = now - dateOfBirth.getTime();
																const ageDate = new Date(diffInMs);
																const age = Math.abs(ageDate.getUTCFullYear() - 1970);
																return age;
															}
															</script>

													</div>
													<div class="col-sm-6" id="CHILDForm" style="display:none;">
														<div class="form-group">
															<label>Parent/Guadian First Name</label>
															<input type="text" name="parentfirstname" required placeholder="First Name" class="form-control">
														</div>
														<div class="form-group">
															<label>Parent/Guadian Last Name</label>
															<input type="text" name="parentlastname" required placeholder="Last Names" class="form-control">
														</div>
														<div class="form-group">
															<label>Phone Number</label>
															<input type="text" required name="phonenumber" placeholder="You Phone Number" class="form-control">
														</div>
														<div class="form-group">
															<label>ID No</label>
															<input type="text" name="idnumber" placeholder="Enter ID Number" class="form-control">
														</div>
														<div class="form-group">
															<label>Residence</label>
															<input type="text" name="residence" placeholder="Residence" class="form-control">
														</div>
														<div class="form-group">
															<label>Visit Date</label>
															<input type="date" required name="visitdate" placeholder="Visit Date" class="form-control">
														</div>					
														<div class="form-group">
															<label>Scheme</label>
															<select name="scheme" required class="form-control">
																<option value="">Choose Scheme</option>
															<?php	if ($result->num_rows > 0) {
																while($row = $result->fetch_assoc()) {
																	echo "<option value='" . $row["pscheme_code"] . "'>" . $row["pscheme_name"] . "</option>";
																}
															} ?>

															</select>
														</div>
														<div class="form-group">
															<label>Member Number (for insurance)</label>
															<input type="text" name="memberno" placeholder="Enter Member No" class="form-control">
														</div>
														<div class="form-group">
															<button name="newpatient" class="btn btn-md btn-primary" type="submit">Add Patient</button>
														</div>													
													</div>
													
													
													
													<div class="col-sm-6" id="ADULTForm" style="display:block;">
														<div class="form-group">
															<label>Phone Number</label>
															<input type="text" required name="phonenumber1" placeholder="You Phone Number" class="form-control">
														</div>
														<div class="form-group">
															<label>ID No</label>
															<input type="text" name="idnumber1" placeholder="Enter ID Number" class="form-control">
														</div>
														<div class="form-group">
															<label>Residence</label>
															<input type="text" name="residence1" placeholder="Residence" class="form-control">
														</div>
														<div class="form-group">
															<label>Visit Date</label>
															<input type="date" required name="visitdate1" placeholder="Visit Date" class="form-control">
														</div>					
														<div class="form-group">
															<label>Scheme</label>
															<select required name="scheme1" class="form-control">
															<option value="">Choose Scheme</option>
															<?php	if ($result1->num_rows > 0) {
																while($row = $result1->fetch_assoc()) {
																	echo "<option value='" . $row["pscheme_code"] . "'>" . $row["pscheme_name"] . "</option>";
																}
															} ?>
															</select>
														</div>
														<div class="form-group">
															<label>Member Number (for insurance)</label>
															<input type="text" name="memberno1" placeholder="Enter Member No" class="form-control">
															
														</div>
														<div class="form-group">
															<input name="newpatient1" class="btn btn-md btn-success" type="submit" value="Adult Patient"/>
														</div>													
													</div>															
													<script>
														const ageCategoryInput = document.getElementById("ageCategory");
														const ADULTForm = document.getElementById("ADULTForm");
														const CHILDForm = document.getElementById("CHILDForm");
														ageCategoryInput.addEventListener("change", function() {
															if (ageCategoryInput.value === "ADULT") {
															const inputDiv = document.querySelector('#CHILDForm');
															const inputs = inputDiv.querySelectorAll('input');
															inputs.forEach(input => {
															input.value = "a";
															});
															ADULTForm.style.display = "block";
															CHILDForm.style.display = "none";
															} 
															else if (ageCategoryInput.value === "CHILD") {
															ADULTForm.style.display = "none";
															CHILDForm.style.display = "block";
															const inputDiv = document.querySelector('#CHILDForm');
															const inputs = inputDiv.querySelectorAll('input');
															inputs.forEach(input => {
															input.value = "";
															});
															} else {
															ADULTForm.style.display = "none";
															CHILDForm.style.display = "none";
															}
														});
														</script>
												</form>
												
											</div>
                                        </div>
						</div>
					 </div>
                </div>
				</div>
        </div>
		<?php include 'includes/footer.php'?>
        </div>
    </div>
   <?php include 'includes/footer-scripts.php';?>
</body>
</html>